CREATE TABLE filmek(kod TEXT, nev TEXT, leiras TEXT, kep1 TEXT, kep2 TEXT, kep3 TEXT, kep4 TEXT, kep5 TEXT, kep6 TEXT, fokep TEXT);

INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("-tGEsyuMnRA", "Dűne: Második rész", "A távoli jövőben, a bolygóközi királyságok korában játszódó történetben két nagyhatalmú uralkodóház harcol az Arrakis bolygó feletti hatalomért, mert az ismert univerzumban egyedül az itteni végtelen sivatagban bányászható az a fűszer, amely lehetővé teszi a csillagközi utazást.", "https://media.port.hu/images/001/620/938.webp", "https://media.port.hu/images/001/620/918.webp", "https://media.port.hu/images/001/620/934.webp", "https://media.port.hu/images/001/620/930.webp", "https://media.port.hu/images/001/620/920.webp", "https://media.port.hu/images/001/620/922.webp", "https://s.24.hu/app/uploads/2024/03/dune2-e1709485726276-1024x576.jpg");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("vbDgdb58l2k", "Kung Fu Panda 4", "Csaknem egy évtized után tavasszal visszatér a legkülönösebb kungfu mester a DreamWorks Animation fergeteges sorozatának baresz új fejezetében. Bátor Sárkányharcosként végigcsinált három halált megvető kalandot, és most a sors újabb feladat elé állítja: pihenjen már egy kicsit. Pontosabban hogy legyen a Békevölgy szellemi vezetője.", "https://media.port.hu/images/001/625/894.webp", "https://media.port.hu/images/001/625/892.webp", "https://media.port.hu/images/001/625/890.webp", "https://media.port.hu/images/001/625/886.webp", "https://media.port.hu/images/001/625/884.webp", "https://media.port.hu/images/001/609/646.webp", "https://i0.wp.com/www.thewrap.com/wp-content/uploads/2023/12/kung-fu-panda-4-image.jpg");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("sETzLAJ7n74", "A kaszkadőr", "Hősünk kaszkadőr, és mint mindenkit a kaszkadőrközösségben, őt is felrobbantják, lelövik, elütik, kidobják ablakokon és leejtik magas helyekről, a mi szórakoztatásunkra.", "https://media.port.hu/images/001/601/072.webp", "https://media.port.hu/images/001/601/074.webp", "https://media.port.hu/images/001/601/076.webp", "https://media.port.hu/images/001/601/078.webp", "https://media.port.hu/images/001/601/072.webp", "https://media.port.hu/images/001/601/076.webp", "https://image.tmdb.org/t/p/original/eFNXMvbgCkfBy35oOjRjgdnkVuk.jpg");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("FXMF_WAEiH4", "Az első ómen", "Egy fiatal amerikai nőt Rómába küldenek, hogy az egyház szolgálatának szentelje életét. Ott azonban olyan sötétséggel találkozik, ami kétségeket ébreszt tulajdon hitében, s egy borzongató összeesküvésre is fényt derít, aminek célja, hogy biztosítsa a megtestesült gonosz világra jövetelét.", "https://media.port.hu/images/001/631/914.webp", "https://media.port.hu/images/001/631/902.webp", "https://media.port.hu/images/001/631/912.webp", "https://media.port.hu/images/001/631/900.webp", "https://media.port.hu/images/001/631/898.webp", "https://media.port.hu/images/001/613/914.webp", "https://www.hollywoodreporter.com/wp-content/uploads/2024/03/TFO-07276-H-2024.jpg");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("gdwlTCp6wWQ", "A méhész", "Egy férfi egyszemélyes, brutális bosszúhadjáratának tétje országos szintűre nő, miután kiderül róla, hogy korábban a Méhészek néven ismert befolyásos és titkos szervezet ügynöke volt.", "https://media.port.hu/images/001/607/728.webp", "https://media.port.hu/images/001/607/724.webp", "https://media.port.hu/images/001/607/718.webp", "https://media.port.hu/images/001/607/712.webp", "https://media.port.hu/images/001/607/708.webp", "https://media.port.hu/images/001/607/710.webp", "https://kep.cdn.index.hu/1/0/5441/54416/544163/54416347_4020007_70f6d07f7dbd52efeb4faabe1eeedb60_wm.jpg");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("bw_PgBizOoQ", "Wonka", "Willy Wonka (Timothée Chalamet) igazi legenda. De még a legendák is voltak fiatalok. Csak egészen másképpen, mint bármelyik másik ember. Végre lehull a lepel a csokik mágusa, az édességek géniusza, a legkülönlegesebb, legízesebb, legfurább csokigyáros, Willy Wonka életének nagy titkáról.", "https://media.port.hu/images/001/609/440.webp", "https://media.port.hu/images/001/602/436.webp", "https://media.port.hu/images/001/609/438.webp", "https://media.port.hu/images/001/609/436.webp", "https://media.port.hu/images/001/609/434.webp", "https://media.port.hu/images/001/609/432.webp", "https://media-cldnry.s-nbcnews.com/image/upload/t_social_share_1200x630_center,f_auto,q_auto:best/rockcms/2023-12/willy-wonka-mc-231211-03-2b6c32.jpg");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("P-pA_gVjeTM", "Argylle: A szuperkém", "Minél nagyobb a kém, annál nagyobb a hazugság. Matthew Vaughn (a Kingsman-filmek, Ha-Ver) újabb eszelős agymenése az Argylle: A szuperkém, ez a fékezhetetlenül szellemes, a valóságot kicsavaró, a világot körbecikázó kémthriller.", "https://media.port.hu/images/001/609/126.webp", "https://media.port.hu/images/001/609/128.webp", "https://media.port.hu/images/001/614/532.webp", "https://media.port.hu/images/001/614/522.webp", "https://media.port.hu/images/001/614/518.webp", "https://media.port.hu/images/001/609/580.webp", "https://www.hollywoodreporter.com/wp-content/uploads/2022/09/Argylle-Lipa-Cavill-Still-Apple-TV-Publicity-H-2022.jpg?w=1296");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("", "", "", "", "", "", "", "", "", "");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("", "", "", "", "", "", "", "", "", "");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("", "", "", "", "", "", "", "", "", "");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("", "", "", "", "", "", "", "", "", "");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("", "", "", "", "", "", "", "", "", "");
INSERT INTO filmek(kod, nev, leiras, kep1, kep2, kep3, kep4, kep5, kep6, fokep) VALUES("", "", "", "", "", "", "", "", "", "");
















